# Generated by Django 4.0.4 on 2022-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleSheetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.IntegerField(db_column='заказ №')),
                ('price', models.IntegerField(db_column='стоимость,$')),
                ('date_delivery', models.DateField(db_column='срок поставки')),
                ('price_rub', models.FloatField(db_column='стоимость в руб.')),
            ],
        ),
    ]
